apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issureRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.com #domain name
  dnsName:
    - k8s-multi.com
    - www.k8s-multi.com
  acme:
    config:
      - http01:
          ingressClas: nginx
        domains:
          - k8s-multi.com
          - www.k8s-multi.com
